[package]
name = "crunch-support"
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true

[dependencies]
crunch-config = { path = "../config" }

serde_json = { workspace = true }
subxt = { workspace = true }
