#!/bin/bash
#
# > make a file executable
# chmod +x ./pre-commit
#
set -e

echo "Run check formatting"
cargo fmt --all -- --check

# echo "Run clippy"
# cargo clippy --all-targets -- -D warnings

# echo "Run tests"
# cargo test
