[package]
name = "crunch-matrix"
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true

[dependencies]
crunch-config = { path = "../config" }
crunch-support = { path = "../support" }

async-recursion = { workspace = true }
base64 = { workspace = true }
log = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
subxt = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }
