[package]
name = "crunch-kusama"
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true

[dependencies]
crunch-core = { path = "../../core" }
crunch-config = { path = "../../config" }
crunch-error = { path = "../../error" }
crunch-report = { path = "../../report" }
crunch-stats = { path = "../../stats" }
crunch-asset-hub-kusama = { path = "../asset-hub-kusama" }
crunch-people-kusama = { path = "../people-kusama" }
crunch-relay-chain-kusama = { path = "../relay-chain-kusama" }

async-recursion = { workspace = true }
log = { workspace = true }
subxt = { workspace = true }
subxt-signer = { workspace = true }
