[package]
name = "crunch-core"
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true

[dependencies]
crunch-config = { path = "../config" }
crunch-matrix = { path = "../matrix" }
crunch-support = { path = "../support" }
crunch-error = { path = "../error" }

async-std = { workspace = true }
env_logger = { workspace = true }
hex = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sp-core = { workspace = true }
subxt = { workspace = true }
subxt-signer = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
