[package]
name = "crunch-polkadot"
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true

[dependencies]
crunch-core = { path = "../../core" }
crunch-config = { path = "../../config" }
crunch-error = { path = "../../error" }
crunch-report = { path = "../../report" }
crunch-stats = { path = "../../stats" }
crunch-people-polkadot = { path = "../people-polkadot" }
crunch-relay-chain-polkadot = { path = "../relay-chain-polkadot" }

async-recursion = { workspace = true }
log = { workspace = true }
subxt = { workspace = true }
subxt-signer = { workspace = true }
