[package]
name = "crunch-error"
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true

[dependencies]
crunch-matrix = { path = "../matrix" }

codec = { workspace = true }
url = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
subxt = { workspace = true }
subxt-signer = { workspace = true }
reqwest = { workspace = true }
thiserror = { workspace = true }
